[package]
name = "kusostat"
version = "0.1.0"
authors = ["yammmt <cu.cs.y20@gmail.com>"]
edition = "2018"

[dependencies]
actix-files = "0.5.0"
actix-web = "3.3.2"
diesel = { version = "1.4.5", features = ["postgres"] }
dotenv = "0.15.0"
tera = "1.6.0"
